"""add code repositories and code chunk metadata

Revision ID: 86ee19e24008
Revises: 25f7b497eadc
Create Date: 2026-08-14 15:47:40.224535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ee19e24008'
down_revision: Union[str, Sequence[str], None] = '25f7b497eadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('zip_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_repositories_id'), 'code_repositories', ['id'], unique=False)
    op.add_column('document_chunks', sa.Column('code_fqn', sa.String(length=500), nullable=True))
    op.add_column('document_chunks', sa.Column('code_kind', sa.String(length=20), nullable=True))
    op.add_column('document_chunks', sa.Column('start_line', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_line', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_chunks_code_fqn'), 'document_chunks', ['code_fqn'], unique=False)
    op.add_column('documents', sa.Column('source_type', sa.String(length=20), server_default='pdf', nullable=False))
    op.add_column('documents', sa.Column('code_repository_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'code_repositories', ['code_repository_id'], ['id'])

    # HNSW needs pgvector extension >= 0.5.0. If yours is older,
    # swap for the ivfflat variant in the comment below.
    op.execute(
        "CREATE INDEX IF NOT EXISTS document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    # ivfflat fallback (pgvector < 0.5.0):
    # "CREATE INDEX ... USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"

    op.execute(
        "CREATE INDEX IF NOT EXISTS document_chunks_search_vector_gin "
        "ON document_chunks USING gin (search_vector)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'code_repository_id')
    op.drop_column('documents', 'source_type')
    op.drop_index(op.f('ix_document_chunks_code_fqn'), table_name='document_chunks')
    op.drop_column('document_chunks', 'end_line')
    op.drop_column('document_chunks', 'start_line')
    op.drop_column('document_chunks', 'code_kind')
    op.drop_column('document_chunks', 'code_fqn')
    op.drop_index(op.f('ix_code_repositories_id'), table_name='code_repositories')
    op.drop_table('code_repositories')
    # ### end Alembic commands ###
