"""add revoked to refresh tokens

Revision ID: 93b8fb037606
Revises: 4803db95d23d
Create Date: 2026-08-10 11:58:27.991729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b8fb037606'
down_revision: Union[str, Sequence[str], None] = '4803db95d23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'refresh_tokens',
    sa.Column(
        'revoked',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###
